const translations = {
    ro: {
        title: "Calculator de Consum de Combustibil",
        startLabel: "Punct de plecare:",
        startPlaceholder: "Introduceti locatia de plecare",
        endLabel: "Destinatie:",
        endPlaceholder: "Introduceti destinatia",
        efficiencyLabel: "Consum de combustibil (L/100km):",
        calculateButton: "Calculeaza Ruta",
        distanceLabel: "Distanta totala:",
        durationLabel: "Durata estimata:",
        fuelLabel: "Consum total de combustibil:",
        downloadButton: "Descarcă Raport PDF",
        km: "km",
        minutes: "minute",
        liters: "litri",
        addRoute: "Adauga Ruta",
        generateReport: "Genereaza Raport PDF",
        routeTitle: "Ruta",
        reportTitle: "Raport de Consum de Combustibil",
        totalTitle: "Total",
        reportGenerated: "Raport generat la"
    },
    en: {
        title: "Fuel Consumption Calculator",
        startLabel: "Starting Point:",
        startPlaceholder: "Enter starting location",
        endLabel: "Destination:",
        endPlaceholder: "Enter destination",
        efficiencyLabel: "Fuel Efficiency (L/100km):",
        calculateButton: "Calculate Route",
        distanceLabel: "Total Distance:",
        durationLabel: "Estimated Duration:",
        fuelLabel: "Total Fuel Consumption:",
        downloadButton: "Download PDF Report",
        km: "km",
        minutes: "minutes",
        liters: "liters",
        addRoute: "Add Route",
        generateReport: "Generate PDF Report",
        routeTitle: "Route",
        reportTitle: "Fuel Consumption Report",
        totalTitle: "Total",
        reportGenerated: "Report generated at"
    }
}; 